# 数据库配置
database:
  type: postgresql
  path: ~/media_analyzer/sqlite/test_media_index.db
  postgres:
    host: localhost
    port: 5432
    database: media_analyzer_test
    username: postgres
    password: postgres
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

# 日志配置
logging:
  level: DEBUG
  path: ~/media_analyzer/logs
  max_size: 10485760
  backup_count: 5
  format: '%(asctime)s [%(levelname)s] %(message)s'

# 扫描配置
scan:
  max_depth: 10
  exclude_dirs:
    - .git
    - .svn
    - node_modules
    - __pycache__
  include_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
    - .tiff
    - .mp4
    - .mov
    - .avi
    - .mkv

# 同步配置
sync:
  interval: 5  # 测试时使用更短的同步间隔
  timeout: 10
  retry_count: 2
  batch_size: 100

# 系统配置
system:
  id: test-system
  temp_dir: /tmp/media_analyzer_test
  max_workers: 2 