# 数据库配置
database:
  type: postgresql
  path: ~/media_analyzer/sqlite/media_index.db  # 仅用于迁移时的SQLite数据库路径
  postgres:
    host: localhost  # 本地环境使用localhost
    port: 5432
    database: media_analyzer
    username: postgres
    password: postgres
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600
  # Docker配置
  docker:
    # 通用配置
    common:
      port: 5433  # 映射到主机的端口
      username: postgres
      password: postgres
      database: media_analyzer
      container_name: postgres-db
    # macOS专用配置
    macos:
      version: '3.8'
      build_context: true  # 是否使用build而不是image
      image: postgres:14
      healthcheck: true
      volume_name: postgres_data
    # Linux专用配置  
    linux:
      version: '3'
      build_context: false
      image: postgres:14
      healthcheck: false
      volume_name: postgres-data
    # Windows专用配置
    windows:
      version: '3'
      build_context: false
      image: postgres:14
      healthcheck: false
      volume_name: postgres-data
      env_vars_format: direct  # 在Windows上不使用环境变量替换语法

# 日志配置
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  path: ~/media_analyzer/logs
  max_size: 10485760  # 10MB
  backup_count: 5
  format: '%(asctime)s [%(levelname)s] %(message)s'

# 扫描配置
scan:
  max_depth: 10  # 扫描目录的最大深度
  exclude_dirs:  # 排除的目录
    - .git
    - .svn
    - node_modules
    - __pycache__
    - Library
    - .local
    - .cache
    - .npm
    - .vscode
  include_extensions:  # 包含的文件扩展名
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
    - .tiff
    - .mp4
    - .mov
    - .avi
    - .mkv
  include_home: true   # 是否包含扫描用户主目录
  home_scan_dirs:      # 在主目录下要扫描的目录列表(空列表表示全部扫描)
    - Pictures
    - Downloads
    - Documents
    - Videos
    - Desktop

# 同步配置
sync:
  interval: 300
  timeout: 30
  retry_count: 3
  batch_size: 1000

# 系统配置
system:
  id: auto
  temp_dir: /tmp/media_analyzer
  max_workers: 4 